//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTraineeAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public string name { get; set; }
        public int category_id { get; set; }
        public int price { get; set; }
        public int quantity { get; set; }
        public string short_description { get; set; }
        public string long_description { get; set; }
        public string small_image { get; set; }
        public string large_image { get; set; }
        public bool is_deleted { get; set; }
        public int created_by { get; set; }
        public System.DateTime created_date { get; set; }
        public int updated_by { get; set; }
        public System.DateTime updated_date { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
