//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAssignment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public int VehicleId { get; set; }
        public int MechanicId { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public System.DateTime date { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
    
        public virtual Mechanic Mechanic { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
