//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlAssignment1.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationForm
    {
        public int registration_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public long phone { get; set; }
        public byte gender { get; set; }
        public string password { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}
