USE [master]
GO

/****** Object:  Database [SourceControlAssignment1]    Script Date: 27-11-2020 04:44:31 PM ******/
CREATE DATABASE [SourceControlAssignment1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SourceControlAssignment1', FILENAME = N'C:\Users\aliabbas\SourceControlAssignment1.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SourceControlAssignment1_log', FILENAME = N'C:\Users\aliabbas\SourceControlAssignment1_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SourceControlAssignment1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SourceControlAssignment1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET ARITHABORT OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SourceControlAssignment1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SourceControlAssignment1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SourceControlAssignment1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SourceControlAssignment1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SourceControlAssignment1] SET  MULTI_USER 
GO

ALTER DATABASE [SourceControlAssignment1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SourceControlAssignment1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SourceControlAssignment1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SourceControlAssignment1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SourceControlAssignment1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SourceControlAssignment1] SET QUERY_STORE = OFF
GO

USE [SourceControlAssignment1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [SourceControlAssignment1] SET  READ_WRITE 
GO

